// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VGameBoySoC.h for the primary calling header

#ifndef VERILATED_VGAMEBOYSOC___024ROOT_H_
#define VERILATED_VGAMEBOYSOC___024ROOT_H_  // guard

#include "verilated.h"


class VGameBoySoC__Syms;

class alignas(VL_CACHE_LINE_BYTES) VGameBoySoC___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_dbg_opcode,7,0);
        VL_OUT8(io_dbg_a,7,0);
        VL_OUT8(io_dbg_f,7,0);
        VL_OUT8(io_dbg_b,7,0);
        VL_OUT8(io_dbg_c,7,0);
        VL_OUT8(io_dbg_d,7,0);
        VL_OUT8(io_dbg_e,7,0);
        VL_OUT8(io_dbg_h,7,0);
        VL_OUT8(io_dbg_l,7,0);
        VL_OUT8(io_dbg_state,7,0);
        VL_OUT8(io_dbg_tcycle,7,0);
        VL_OUT8(io_dbg_mcycle,7,0);
        VL_OUT8(io_dbg_IR,7,0);
        VL_OUT8(io_dbg_ly,7,0);
        VL_IN8(io_extRomLoadData,7,0);
        VL_IN8(io_extRomLoadEn,0,0);
        VL_OUT8(io_pixelValid,0,0);
        VL_OUT8(io_pixelX,7,0);
        VL_OUT8(io_pixelY,7,0);
        VL_OUT8(io_pixelColor,1,0);
        VL_OUT8(io_hblank,0,0);
        VL_OUT8(io_vblank,0,0);
        VL_OUT8(io_lcdEnable,0,0);
        CData/*0:0*/ GameBoySoC__DOT__cpu_io_memWrite;
        CData/*7:0*/ GameBoySoC__DOT__cpu_io_memReadData;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__intr_io_should_irq;
        CData/*3:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_op;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_a;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_b;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_carryIn;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_out;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_flagZ;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_flagN;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_flagH;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__A;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__F;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__B;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__C;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__D;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__E;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__H;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__L;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__IR;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__IR2;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__imm8;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__CB_imm8;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__IME;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__IME_pending;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__A_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__F_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__B_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__C_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__D_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__E_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__H_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__L_sampled;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__state;
        CData/*1:0*/ GameBoySoC__DOT__cpu__DOT__tcycle;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__mcycle;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__halted;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__canTakeInterrupt;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_tmp8;
    };
    struct {
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_1;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_oldVal;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_59;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_112;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_61;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_115;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_126;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_84;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___u_T_98;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_239;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_250;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_252;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_condition;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_correction;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_adjusted;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_805;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_879;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_939;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1009;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1026;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1168;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1258;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1338;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1576;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1634;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1637;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1638;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1656;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1659;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1700;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1770;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1855;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1856;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u___05Fdone;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FC;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FB;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FE;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FD;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FL;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FH;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FF;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FA;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1926;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1927;
        CData/*1:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1932;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1938;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1945;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1946;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__needsImm8;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__needsImm16;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1997;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2001;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2004;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2005;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2006;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2007;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2008;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2009;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2010;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2011;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2033;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2036;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2039;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2040;
    };
    struct {
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2041;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2042;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2043;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2044;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2045;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2046;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2088;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_result;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_F;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_B;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_C;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_D;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_E;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_H;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_L;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_A;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_done;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2375;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2376;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2379;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2380;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2381;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2382;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2383;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2384;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2385;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2386;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2387;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2394;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2395;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2396;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2397;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2398;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2399;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2400;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2401;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2402;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2404;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2405;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2406;
        CData/*1:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2407;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h54193848__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hb470ae14__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h2973ccb9__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h9292fa83__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hb1f2c5d2__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h7780515d__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h4060f9f5__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h03c34ea4__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hbdd8dcae__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h0f4cf0f6__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h7347a28d__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hfd0c7d8d__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h044855b3__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h2734558b__0;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__intr__DOT__active;
        CData/*3:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__io_flagH_aNib;
        CData/*3:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__io_flagH_bNib;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT___io_flagC_T_2;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__r;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__r_1;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__r_2;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__vram_io_read;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushEnable;
    };
    struct {
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_0;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_1;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_2;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_3;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_4;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_5;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_6;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushPixels_7;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_popEnable;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_clear;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__lyReg;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__vblankIRQ;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___lyReg_T_1;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT___T_5;
        CData/*2:0*/ GameBoySoC__DOT__ppu__DOT__fetcherState;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__fetcherX;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__tileNum;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__tileDataLow;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__tileDataHigh;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__xPos;
        CData/*3:0*/ GameBoySoC__DOT__ppu__DOT__discardPixels;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT___T_11;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__mode;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_15;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_16;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_19;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__scrolledY;
        CData/*2:0*/ GameBoySoC__DOT__ppu__DOT___GEN_87;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_88;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_89;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_99;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___palPx_T;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___xPos_T_1;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_139;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT____VdfgTmp_ha309eb35__0;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__vram__DOT__mem_io_rdata_MPORT_data;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__vram__DOT__mem_io_rdata_MPORT_en_pipe_0;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_0;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_1;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_2;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_3;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_4;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_5;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_6;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_7;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_8;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_9;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_10;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_11;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_12;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_13;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_14;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_15;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_16;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_17;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_18;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_19;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_20;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_21;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_22;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_23;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_24;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_25;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_26;
    };
    struct {
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_27;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_28;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_29;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_30;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_31;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__head;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__tail;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__count;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_21;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_256;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_257;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_258;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_259;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_260;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_261;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_262;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_263;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_264;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_265;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_266;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_267;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_268;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_269;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_270;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_271;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_272;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_273;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_274;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_275;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_276;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_277;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_278;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_279;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_280;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_281;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_282;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_283;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_284;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_285;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_286;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_287;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___tail_T_1;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___head_T_1;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___count_T_1;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___count_T_3;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_544;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_545;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT__ioRegs_io_write;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs_io_writeData;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__wram_MPORT_3_data;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__regIE;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT___T_4;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT___GEN_46;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT___GEN_49;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT___GEN_53;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT___GEN_335;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT____Vlvbound_h5559fb94__0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT____Vlvbound_ha6cb93b5__0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regP1;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSB;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regDIV;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regTIMA;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regTMA;
    };
    struct {
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regTAC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regIF;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_2;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR10;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR11;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR12;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR13;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR14;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR21;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR22;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR23;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR24;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR30;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR31;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR32;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR33;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR34;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR41;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR42;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR43;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR44;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR50;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR51;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR52;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regLCDC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSTAT;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSCY;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSCX;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regLYC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regDMA;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regBGP;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regOBP0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regOBP1;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regWY;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regWX;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regBOOT;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_30;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_43;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_382;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_407;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_433;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_460;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_488;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_517;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_547;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_578;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_644;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_678;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_713;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_749;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_801;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_803;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_804;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_805;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_807;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_808;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_809;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_810;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_811;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_812;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_813;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_814;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_815;
    };
    struct {
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_816;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_817;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_818;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_819;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_820;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_821;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_822;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_823;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_824;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_825;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_826;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_827;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_828;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_829;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_830;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_831;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_832;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_833;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_834;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_835;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_836;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_837;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_838;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_839;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(io_dbg_pc,15,0);
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__PC;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__SP;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__imm16;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__PC_sampled;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__SP_sampled;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_HL;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_result;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_result_1;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_operand;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_result_2;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___u_out_PC_T_4;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_regPair;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1343;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u___05FSP;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1922;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u___05FPC;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1934;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1943;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1944;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1998;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2002;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2003;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2037;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2038;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2373;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2374;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2377;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2378;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2403;
        SData/*8:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__sum9;
        SData/*8:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__sumc9;
        SData/*8:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__diff9;
        SData/*8:0*/ GameBoySoC__DOT__cpu__DOT__u_alu__DOT__diffc9;
        SData/*8:0*/ GameBoySoC__DOT__ppu__DOT__dotCounter;
        SData/*8:0*/ GameBoySoC__DOT__ppu__DOT___dotCounter_T_1;
        SData/*13:0*/ GameBoySoC__DOT__ppu__DOT__tileAddr;
    };
    struct {
        SData/*12:0*/ GameBoySoC__DOT__ppu__DOT__vram__DOT__mem_io_rdata_MPORT_addr_pipe_0;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT__rom_cartRomOut_addr;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT___GEN_434;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__divCounter;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___divCounter_T_1;
        VL_IN(io_extRomLoadAddr,31,0);
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*7:0*/, 8192> GameBoySoC__DOT__ppu__DOT__vram__DOT__mem;
        VlUnpacked<CData/*7:0*/, 65536> GameBoySoC__DOT__memory__DOT__rom;
        VlUnpacked<CData/*7:0*/, 8192> GameBoySoC__DOT__memory__DOT__wram;
        VlUnpacked<CData/*7:0*/, 160> GameBoySoC__DOT__memory__DOT__oam;
        VlUnpacked<CData/*7:0*/, 127> GameBoySoC__DOT__memory__DOT__hram;
        VlUnpacked<CData/*0:0*/, 2> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VGameBoySoC__Syms* const vlSymsp;

    // CONSTRUCTORS
    VGameBoySoC___024root(VGameBoySoC__Syms* symsp, const char* v__name);
    ~VGameBoySoC___024root();
    VL_UNCOPYABLE(VGameBoySoC___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
