// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VGameBoySoC.h for the primary calling header

#ifndef VERILATED_VGAMEBOYSOC___024ROOT_H_
#define VERILATED_VGAMEBOYSOC___024ROOT_H_  // guard

#include "verilated.h"


class VGameBoySoC__Syms;

class alignas(VL_CACHE_LINE_BYTES) VGameBoySoC___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_dbg_opcode,7,0);
        VL_OUT8(io_dbg_a,7,0);
        VL_OUT8(io_dbg_f,7,0);
        VL_OUT8(io_dbg_b,7,0);
        VL_OUT8(io_dbg_c,7,0);
        VL_OUT8(io_dbg_d,7,0);
        VL_OUT8(io_dbg_e,7,0);
        VL_OUT8(io_dbg_h,7,0);
        VL_OUT8(io_dbg_l,7,0);
        VL_OUT8(io_dbg_state,7,0);
        VL_OUT8(io_dbg_tcycle,7,0);
        VL_OUT8(io_dbg_mcycle,7,0);
        VL_OUT8(io_dbg_IR,7,0);
        VL_OUT8(io_dbg_ly,7,0);
        VL_IN8(io_extRomLoadData,7,0);
        VL_IN8(io_extRomLoadEn,0,0);
        VL_OUT8(io_pixelValid,0,0);
        VL_OUT8(io_pixelX,7,0);
        VL_OUT8(io_pixelY,7,0);
        VL_OUT8(io_pixelColor,1,0);
        VL_OUT8(io_hblank,0,0);
        VL_OUT8(io_vblank,0,0);
        VL_OUT8(io_lcdEnable,0,0);
        CData/*0:0*/ GameBoySoC__DOT__cpu_io_memWrite;
        CData/*7:0*/ GameBoySoC__DOT__cpu_io_memReadData;
        CData/*0:0*/ GameBoySoC__DOT__ppu_io_vramRead;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__intr_io_should_irq;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__intr_io_irq_index;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_alu_io_out;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__A;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__F;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__B;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__C;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__D;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__E;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__H;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__L;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__IR;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__IR2;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__imm8;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__CB_imm8;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__IME;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__IME_pending;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__A_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__F_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__B_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__C_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__D_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__E_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__H_sampled;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__L_sampled;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__state;
        CData/*1:0*/ GameBoySoC__DOT__cpu__DOT__tcycle;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__mcycle;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__canTakeInterrupt;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__irqIndexLatched;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_tmp8;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_1;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_75;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_76;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_77;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_78;
    };
    struct {
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_79;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_80;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_81;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_59;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_61;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_115;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_133;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___u_T_84;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___u_T_98;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_239;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_250;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_254;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_331;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT__u_condition;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u_adjusted;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1863;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FC;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FB;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FE;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FD;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FL;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FH;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FF;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__u___05FA;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__state_prev;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT__mcycle_prev;
        CData/*1:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1942;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1948;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1955;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1956;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2020;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2024;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2028;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2029;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2030;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2031;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2032;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2033;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2034;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2035;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2060;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2063;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2066;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2067;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2068;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2069;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2070;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2071;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2072;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2073;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_F;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_B;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_C;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_D;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_E;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_H;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_L;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT__cbOut_A;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2420;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2421;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2424;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2425;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2426;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2427;
    };
    struct {
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2428;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2429;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2430;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2431;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2432;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2439;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2440;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2441;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2442;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2443;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2444;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2445;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2446;
        CData/*7:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2447;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2449;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2450;
        CData/*2:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2453;
        CData/*1:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2454;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h2734558b__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h044855b3__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hfd0c7d8d__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h7347a28d__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h0f4cf0f6__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hbdd8dcae__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h03c34ea4__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h4060f9f5__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h7780515d__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hb1f2c5d2__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h9292fa83__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_h2973ccb9__0;
        CData/*0:0*/ GameBoySoC__DOT__cpu__DOT____VdfgTmp_hb470ae14__0;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__vram_io_rdata;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_pushEnable;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_popEnable;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO_io_clear;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__lyReg;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT__vblankIRQ;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___lyReg_T_1;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT___T_5;
        CData/*2:0*/ GameBoySoC__DOT__ppu__DOT__fetcherState;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__fetcherX;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__tileNum;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__tileDataLow;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__tileDataHigh;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__xPos;
        CData/*3:0*/ GameBoySoC__DOT__ppu__DOT__discardPixels;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT___T_11;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__mode;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT___T_37;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_15;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_16;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_19;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT__scrolledY;
        CData/*2:0*/ GameBoySoC__DOT__ppu__DOT___GEN_87;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_88;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_89;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_99;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___xPos_T_1;
        CData/*7:0*/ GameBoySoC__DOT__ppu__DOT___GEN_174;
        CData/*0:0*/ GameBoySoC__DOT__ppu__DOT____VdfgTmp_ha309eb35__0;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_0;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_1;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_2;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_3;
    };
    struct {
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_4;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_5;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_6;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_7;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_8;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_9;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_10;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_11;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_12;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_13;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_14;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_15;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_16;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_17;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_18;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_19;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_20;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_21;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_22;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_23;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_24;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_25;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_26;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_27;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_28;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_29;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_30;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__fifo_31;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__head;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__tail;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT__count;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_256;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_257;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_258;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_259;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_260;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_261;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_262;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_263;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_264;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_265;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_266;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_267;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_268;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_269;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_270;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_271;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_272;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_273;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_274;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_275;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_276;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_277;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_278;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_279;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_280;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_281;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_282;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_283;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_284;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_285;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_286;
        CData/*1:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_287;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___tail_T_1;
    };
    struct {
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___head_T_1;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___count_T_1;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___count_T_3;
        CData/*4:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_544;
        CData/*5:0*/ GameBoySoC__DOT__ppu__DOT__pixelFIFO__DOT___GEN_545;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs_io_addr;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT__ioRegs_io_write;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs_io_writeData;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT__timer_io_enable;
        CData/*1:0*/ GameBoySoC__DOT__memory__DOT__timer_io_addr;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT__timer_io_write;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__timer_io_wdata;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__wram_MPORT_3_data;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__regIE;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT___GEN_534;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT____Vlvbound_h5559fb94__0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT____Vlvbound_ha6cb93b5__0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regP1;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSB;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regIF;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR10;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR11;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR12;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR13;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR14;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR21;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR22;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR23;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR24;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR30;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR31;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR32;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR33;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR34;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR41;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR42;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR43;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR44;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR50;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR51;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regNR52;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regLCDC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSTAT;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSCY;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regSCX;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regLYC;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regDMA;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regBGP;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regOBP0;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regOBP1;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regWY;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regWX;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT__regBOOT;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_648;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_650;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_651;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_652;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_653;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_654;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_655;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_656;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_657;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_658;
    };
    struct {
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_659;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_660;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_661;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_662;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_663;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_664;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_665;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_666;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_667;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_668;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_669;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_670;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_671;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_672;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_673;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_674;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_675;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_676;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_677;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_678;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_679;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_680;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_681;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_682;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___GEN_726;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___regIF_T;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__ioRegs__DOT___regIF_T_2;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT__tima;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT__tma;
        CData/*2:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT__tac;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT__prev;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT___GEN_3;
        CData/*7:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT___GEN_6;
        CData/*2:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT___GEN_7;
        CData/*0:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT____VdfgTmp_h3326f5f0__0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactContinue;
        VL_OUT16(io_dbg_pc,15,0);
        SData/*15:0*/ GameBoySoC__DOT__cpu_io_memAddr;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__intr_io_irq_vector;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__PC;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__SP;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__imm16;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__PC_sampled;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__SP_sampled;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__irqVectorLatched;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_HL;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_result;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_result_1;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT__u_result_2;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___u_out_H_T_8;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1944;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1953;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_1954;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2021;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2026;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2027;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2064;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2065;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2418;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2419;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2422;
    };
    struct {
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2423;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2448;
        SData/*15:0*/ GameBoySoC__DOT__cpu__DOT___GEN_2452;
        SData/*8:0*/ GameBoySoC__DOT__ppu__DOT__dotCounter;
        SData/*8:0*/ GameBoySoC__DOT__ppu__DOT___dotCounter_T_1;
        SData/*13:0*/ GameBoySoC__DOT__ppu__DOT__tileAddr;
        SData/*12:0*/ GameBoySoC__DOT__ppu__DOT__vram__DOT__mem_io_rdata_MPORT_addr_pipe_0;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT__div;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT___div_T_1;
        SData/*15:0*/ GameBoySoC__DOT__memory__DOT__timer__DOT___prev_T;
        VL_IN(io_extRomLoadAddr,31,0);
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*7:0*/, 8192> GameBoySoC__DOT__ppu__DOT__vram__DOT__mem;
        VlUnpacked<CData/*7:0*/, 65536> GameBoySoC__DOT__memory__DOT__rom;
        VlUnpacked<CData/*7:0*/, 8192> GameBoySoC__DOT__memory__DOT__wram;
        VlUnpacked<CData/*7:0*/, 160> GameBoySoC__DOT__memory__DOT__oam;
        VlUnpacked<CData/*7:0*/, 127> GameBoySoC__DOT__memory__DOT__hram;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    VGameBoySoC__Syms* const vlSymsp;

    // CONSTRUCTORS
    VGameBoySoC___024root(VGameBoySoC__Syms* symsp, const char* v__name);
    ~VGameBoySoC___024root();
    VL_UNCOPYABLE(VGameBoySoC___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
